AWSTemplateFormatVersion: 2010-09-09
Description: Deploys an EFS file system and efs-provisioner (qs-1pipqrqhi)

Parameters:
  HelmLambdaArn:
    Type: String
  ClusterName:
    Type: String
  InitialNodeGroupSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  ProvisionedThroughputInMibps:
    Type: Number
  PrivateSubnet1ID:
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2ID:
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet3ID:
    Type: AWS::EC2::Subnet::Id

Resources:
  EFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties: 
      Encrypted: true
      FileSystemTags:
      - Key: Name
        Value: cloudbees-core-efs-filesystem
      PerformanceMode: generalPurpose
      ProvisionedThroughputInMibps: !Ref ProvisionedThroughputInMibps
      ThroughputMode: provisioned
  MountTargetPrivateSubnet1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SecurityGroups: [ !Ref InitialNodeGroupSecurityGroup ]
      SubnetId: !Ref PrivateSubnet1ID
  MountTargetPrivateSubnet2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SecurityGroups: [ !Ref InitialNodeGroupSecurityGroup ]
      SubnetId: !Ref PrivateSubnet2ID
  MountTargetPrivateSubnet3:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SecurityGroups: [ !Ref InitialNodeGroupSecurityGroup ]
      SubnetId: !Ref PrivateSubnet3ID
  EFSProvisioner:
    Type: "Custom::Helm"
    Version: '1.0'
    Properties:
      ServiceToken: !Ref HelmLambdaArn
      ClusterName: !Ref ClusterName
      Chart: stable/efs-provisioner
      Name: efs-provisioner
      Namespace: efs-provisioner
      Values:
        efsProvisioner.efsFileSystemId: !Ref EFSFileSystem
        efsProvisioner.awsRegion: !Ref "AWS::Region"
        efsProvisioner.provisionerName: aws-quickstart/aws-efs
        efsProvisioner.storageClass.name: aws-efs
        nodeSelector.partition: masters

Outputs:
  EFSFileSystemID:
    Description: EFS file system ID
    Value: !Ref EFSFileSystem